### ISSUE TITLE
Does WebViewJar support Arm64 platform ?

### ISSUE THREAD

**Issue by gaorongfu** [shannah/webviewjar#2]
I try to build it on unbuntu 64bit for arm64, and the hardware is raspberry PI 3B+. when I run build_linux.sh,  I got the error such like Couldn't load library webview...

**Comment by gaorongfu** [comment]
Sorry, That exception is throw when I run these test:
java -jar WebView.jar http://www.baidu.com

**Comment by gaorongfu** [comment]
java.io.IOException: Couldn't load library library webview
	at ca.weblite.webview.nativelib.NativeLoader.loadLibrary(NativeLoader.java:141)
	at ca.weblite.webview.WebViewNative.<clinit>(WebViewNative.java:24)
	at ca.weblite.webview.WebView.show(WebView.java:230)
	at ca.weblite.webview.WebViewCLI.init(WebViewCLI.java:66)
	at ca.weblite.webview.WebViewCLI.main(WebViewCLI.java:314)
Caused by: java.lang.UnsatisfiedLinkError: no webview in java.library.path: [/usr/java/packages/lib, /usr/lib/aarch64-linux-gnu/jni, /lib/aarch64-linux-gnu, /usr/lib/aarch64-linux-gnu, /usr/lib/jni, /lib, /usr/lib]
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
	at java.base/java.lang.System.loadLibrary(System.java:1870)
	at ca.weblite.webview.nativelib.NativeLoader.loadLibrary(NativeLoader.java:136)
	... 4 more

Exception in thread "main" java.lang.UnsatisfiedLinkError: 'long ca.weblite.webview.WebViewNative.webview_create(int, long)'
	at ca.weblite.webview.WebViewNative.webview_create(Native Method)
	at ca.weblite.webview.WebView.show(WebView.java:230)
	at ca.weblite.webview.WebViewCLI.init(WebViewCLI.java:66)
	at ca.weblite.webview.WebViewCLI.main(WebViewCLI.java:314)

**Comment by shannah** [comment]
v1.0+ works on arm
